### ISSUE TITLE
[FEAT] Namespace docker container names

### ISSUE THREAD

**Issue by friggingee** [stratosphereips/stratocyberlab#10]
**Is your feature request related to a problem? Please describe.**
When starting the docker compose setup, the containers have "default" names like "ollama". This can collide with existing containers.

**Describe the solution you'd like**
Namespace the containers like "stratocyberlab-ollama" or something sensible.

**Describe alternatives you've considered**
A clear alternative is to have all other containers on any given machine namespaced to ensure there's no collisions but that seems impractical.

**Additional context**
none

**Comment by HappyStoic** [comment]
Hello @friggingee, thank you for pointing this out, you are absolutely right. We will prefix the names in a near future :+1:
