### ISSUE TITLE
unable to use stratocyberlab

### ISSUE THREAD

**Issue by sai4869** [stratosphereips/stratocyberlab#18]
i am unable to find stratosphereips or anything elce no  matrix no way to communicate or use

**Comment by HappyStoic** [comment]
Hello @sai4869, 

we need more information in order to help you. Did you sign up for [our course](https://cybersecurity.bsy.fel.cvut.cz/) and now you are unable to access Matrix? Did you receive email with instructions? What do you have issues with?

**Comment by sai4869** [comment]
Yes I have registered and started the course but I have no login details or
I don’t have or provided links are not worked I mean the stratocyberlab I
need to have access to use matrix I don’t have them was my approach wrong I
am part of online so plz guide me

**Comment by HappyStoic** [comment]
@sai4869  please check your spam folder - our initial email with instructions could end up there.  

If the email is not in your spam, please write us an email to address 13136-bsy [at] fel.cvut.cz and write us as many details as possible. Our team will handle it. Include also an email address that you used during the eventbrite registration. Thanks!

**Comment by sai4869** [comment]
Hello Stratosphere team

I thank you appreciate for your quick response Now I am able to access
matrix and if u don’t mind can u tell me what is the access room or which
room I need to join and I already have docker installed where can I get
stratocyberlab for link my self with others or go any further in class
based on the link provided  I could not tell to stratocyberlab.online did I
do somethings wrong?

**Comment by verovaleros** [comment]
Hi @sai4869 , did you get the email with the instructions? If yes, did you join Matrix? We sent you emails but you did not answer to any of them asking you to confirm if you receive them. Did you check spam?

**Comment by sai4869** [comment]
I have login to matrix and @extsairamk999249:matrix.org is my id I want to
get back to what wrong I am doing plz guide me

**Comment by LukasForst** [comment]
There's nothing we can do, unless you tell us specific problems. Please contact us on Matrix if you need  some technical guidance. Closing this issue for now.
