### ISSUE TITLE
[BUG] Container class2 would not start, because of -c switch used

### ISSUE THREAD

**Issue by Lubos-source** [stratosphereips/stratocyberlab#5]
**Describe the bug**
`stratocyberlab\classes\class02\dockerfile`
Currently if you try to start class2 via the stratocyberlab interface, the container exits (EXITED) with start.sh not found error. 

**To Reproduce**
Try to start class2 with stratocyberlab and look in docker if it started propetly. You should also look to logs.

**Expected behaviour**
I would expect a class2 container to start.

**Solution**
Because of `-c` it expects the /bin/sh `command`, but start.sh is a script, so you need to start it without the -c switch.
Just edit the Dockerfile:

`CMD /start.sh`
to
`CMD ["/bin/sh", "/start.sh"]`

**Comment by HappyStoic** [comment]
Hello @Lubos-source, 

thank you for reporting the issue and submitting a PR! I appreciate it.

Can you just provide a bit more clarification please? Because the current version is working fine for me, the container for class2 starts, does not exit and the services in the container are running fine. I am testing on Debian 12 and using Docker version 26.0. Can you tell me your environment please so maybe we can prevent this in the future?

Also,  you mention "`-c` switch", what switch exactly do you mean?

**Comment by HappyStoic** [comment]
Sorry for closing the issue, that was a missclick 🙃

**Comment by Lubos-source** [comment]
> Hello @Lubos-source,
> 
> thank you for reporting the issue and submitting a PR! I appreciate it.
> 
> Can you just provide a bit more clarification please? Because the current version is working fine for me, the container for class2 starts, does not exit and the services in the container are running fine. I am testing on Debian 12 and using Docker version 26.0. Can you tell me your environment please so maybe we can prevent this in the future?
> 
> Also, you mention "`-c` switch", what switch exactly do you mean?

Hello, I will provide more information and try to avoid possible problems in the future.

## Environment
My OS: Windows 11 Pro version: 23H2
Using windows subsystem for linux (WSL2)
```
> wsl --version

WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3880
```
Inside WSL2 Iam running Ubuntu
```
> cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```
Docker
```
> docker --version

Docker version 27.1.1, build 6312585
```
Docker desktop on Windows: `Current version: 4.33.1 (161083)`

## -c switch (better **argument**)
class2 image after build up from stratocyberlab interface:
![image](https://github.com/user-attachments/assets/fa7a9ba1-0b9b-4443-91f7-e598227d7693)
When you use `CMD /start.sh` in dockerfile it will use `-c` argument to run command. Which I tought is the problem, so I rewrite docker file to use it directly withou argument.
![image](https://github.com/user-attachments/assets/53ce46df-bae4-4b41-a9c7-d91d760b5604)
I tought there is a problem because `-c` needs command and not a `.sh script`, but today, when I tried to catch logs which I was facing yesterday I found out the **problem was somewhere else.**

## Conclusion
After todays testing You are right the class2 container would start and not fall in exited state even with original dockerfile. 
I dont know why it happend, but bug from yesterday was caused by `CR LF` ending of lines inside `start.sh` file which I had in the file. 
I didn't change the file, but it's possible that the EOL changed after I opened it.
So **my apologies for opening this issue**, after trying downloading the `start.sh` file from github the EOLs are set correctly and others shouldn't run into the same problem unless they manually opens the file.
I didn't think of this simple solution yesterday.

**Comment by HappyStoic** [comment]
Awesome, thanks for the details!
