### ISSUE TITLE
[BUG] docker-compose.yml contains outdated version which triggers WARNING when started

### ISSUE THREAD

**Issue by neodark** [stratosphereips/stratocyberlab#8]
**Describe the bug**
A WARNING is triggered with the  `docker compose up` command

**To Reproduce**
Launch `docker compose up` command and look at the first line (warning output)

**Expected behaviour**
The warning message indicating to remove the obsolete version should disappear

**Screenshots**
None. It is self-explanatory

**Comment by HappyStoic** [comment]
Hello @neodark, thank you for the PR, you are correct! 

The PR is merged ✅
